[entryPoints]
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      # certs used as default certs
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/tls.crt"
      KeyFile = "/ssl/tls.key"
[acme]
email = "oussama_md@hotmail.com"
storageFile = "acme.json"
onDemand = true
caServer = "https://acme-staging.api.letsencrypt.org/directory"
entryPoint = "https"

[[acme.domains]]
  main = "zorend.com"
  sans = ["traefik.zorend.com","k8s.zorend.com","odis.zorend.com", "vurbismarketplace.zorend.com","api.zorend.com"]
[[acme.domains]]
  main = "og.tn"
[[acme.domains]]
  main = "ogov.tn"
  sans = ["api.ogov.tn", "auth.ogov.tn","account.ogov.tn"]
[[acme.domains]]
  main = "soum.tn"
